### ISSUE TITLE
[Meta] Improve on user-experience

### ISSUE THREAD

**Issue by aranas** [alan-turing-institute/teadt-community-survey#39]
## General
- [x] number sections in navigation pane
- [x] hide "Success" page from navigatino pane
- [x] number questions throughout
- [x] for all multiple select questions add instruction "Select all that apply"
- [x] add callout boxes to section descriptions & definitions
- [ ] add alt text to images > not trivial see #87 

## Landing page
- [x] Before Captcha add clear instructions: "To begin the survey, please enter the Captcha below and then press 'Proceed'."
- [ ] Captcha bug #61 

## Consent page
- [ ] ~add a "consent to all questions" button to facilitate consent~ > no time to implement this 

## Current practices
- [x] upon submitting response to `assurance_meaning` disable the editor. We don't want people to go back and adapt their response after seeing our definition

## Goals & Frameworks
- [x] Gemini Principles, provide easy reference to the definitions next to where people need to indicate their choices, especially for those who don't know them well (could be hover but maybe even right next to it)
- [x] make question about challenging dependent on relevance such that those principles that don't apply in a given sector are not rated for challenge

## ABA
- [x] replace example picture of assurance argument
